/**
 * FindingTable — List of behavioral threat detection findings.
 *
 * Renders the table view for detection findings directly returned by the backend API.
 * Displays Severity, Rule & Category, Description, Agent ID, Session ID, Status,
 * Detection Timestamp, and MITRE ATT&CK technique IDs.
 *
 * Feature Folder Pattern:
 *   Located under `pages/Findings/components/` as it is feature-specific.
 */

import Badge from '../../../components/ui/Badge'
import type { Finding, FindingSeverity, FindingStatus } from '../../../types/finding'
import { formatTimestamp } from '../../../utils/date'

interface FindingTableProps {
  findings: Finding[]
  loading: boolean
}

/** Map FindingSeverity to Badge variant */
function severityBadgeVariant(severity: FindingSeverity): 'error' | 'warning' | 'info' | 'muted' {
  switch (severity) {
    case 'CRITICAL':
    case 'HIGH':
      return 'error'
    case 'MEDIUM':
      return 'warning'
    case 'LOW':
    case 'INFO':
      return 'info'
    default:
      return 'muted'
  }
}

/** Map FindingStatus to Badge variant */
function statusBadgeVariant(status: FindingStatus): 'warning' | 'info' | 'active' | 'muted' {
  switch (status) {
    case 'OPEN':
      return 'warning'
    case 'ACKNOWLEDGED':
      return 'info'
    case 'RESOLVED':
      return 'active'
    case 'FALSE_POSITIVE':
    default:
      return 'muted'
  }
}

export default function FindingTable({ findings, loading }: FindingTableProps) {
  if (loading) {
    return (
      <div className="divide-y divide-border-secondary">
        <div className="grid grid-cols-6 gap-4 px-6 py-4 bg-bg-secondary text-xs font-semibold text-text-muted uppercase">
          <span>Severity</span>
          <span>Rule / Category</span>
          <span>Description</span>
          <span>Agent / Session</span>
          <span>Status</span>
          <span>Detected At</span>
        </div>
        {[1, 2, 3].map((n) => (
          <div key={n} className="grid grid-cols-6 gap-4 px-6 py-4 items-center">
            <div className="h-4 w-16 bg-border-primary/40 rounded animate-pulse" />
            <div className="h-4 w-28 bg-border-primary/40 rounded animate-pulse" />
            <div className="h-4 w-48 bg-border-primary/40 rounded animate-pulse" />
            <div className="h-4 w-32 bg-border-primary/40 rounded animate-pulse" />
            <div className="h-4 w-16 bg-border-primary/40 rounded animate-pulse" />
            <div className="h-4 w-32 bg-border-primary/40 rounded animate-pulse" />
          </div>
        ))}
      </div>
    )
  }

  if (findings.length === 0) {
    return (
      <div className="px-6 py-16 text-center space-y-2 bg-bg-surface">
        <h3 className="text-sm font-bold text-text-primary">
          No findings detected
        </h3>
        <p className="text-xs text-text-secondary max-w-sm mx-auto">
          No security findings match the selected criteria or have been generated by the Detection Engine.
        </p>
      </div>
    )
  }

  return (
    <div className="overflow-x-auto w-full">
      <table className="w-full text-left border-collapse min-w-[850px]">
        <thead>
          <tr className="bg-bg-secondary border-b border-border-secondary text-xs font-semibold text-text-muted uppercase tracking-wider select-none">
            <th className="px-6 py-4">Severity</th>
            <th className="px-6 py-4">Rule & Category</th>
            <th className="px-6 py-4">Description</th>
            <th className="px-6 py-4">Agent / Session</th>
            <th className="px-6 py-4">Status</th>
            <th className="px-6 py-4">Detected At</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-border-secondary text-xs">
          {findings.map((finding) => (
            <tr key={finding.id} className="hover:bg-bg-surface-hover/30 transition-colors">
              {/* Severity */}
              <td className="px-6 py-4 whitespace-nowrap">
                <Badge label={finding.severity} variant={severityBadgeVariant(finding.severity)} />
              </td>

              {/* Rule Name & Category & MITRE Techniques */}
              <td className="px-6 py-4 space-y-1">
                <div className="font-semibold text-text-primary">{finding.rule_name}</div>
                <div className="flex flex-wrap gap-1 items-center">
                  <Badge label={finding.category} variant="muted" className="text-[10px]" />
                  {finding.mitre_techniques && finding.mitre_techniques.map((tech) => (
                    <Badge key={tech} label={tech} variant="info" className="text-[10px]" />
                  ))}
                </div>
              </td>

              {/* Description */}
              <td className="px-6 py-4 text-text-secondary max-w-md leading-relaxed">
                {finding.description}
              </td>

              {/* Agent ID & Session ID */}
              <td className="px-6 py-4 space-y-1 font-mono text-[11px]">
                <div className="text-text-primary" title={`Agent ID: ${finding.agent_id}`}>
                  Agent: {finding.agent_id}
                </div>
                <div className="text-text-muted" title={`Session ID: ${finding.session_id}`}>
                  Sess: {finding.session_id}
                </div>
              </td>

              {/* Status */}
              <td className="px-6 py-4 whitespace-nowrap">
                <Badge label={finding.status} variant={statusBadgeVariant(finding.status)} />
              </td>

              {/* Detected At */}
              <td className="px-6 py-4 font-mono text-text-secondary whitespace-nowrap">
                {formatTimestamp(finding.detected_at)}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
