/**
 * approval.ts — Approval Queue domain types.
 *
 * Type contracts for pending approval tickets generated by the Enforcement
 * Engine (ADR-019, ADR-020). These types will be populated when the Approval
 * Queue API ships in PR #71 (Vertical Slice 4).
 *
 * Backend sources:
 *   GET  /api/v1/approvals/pending
 *   POST /api/v1/approvals/:id/release
 *   POST /api/v1/approvals/:id/reject
 *
 * Console surface: /approvals — Approval Queue
 *
 * Feature gate: ENFORCEMENT_ENGINE_ENABLED (src/config/featureFlags.ts)
 */

/** Current state of a pending approval ticket. */
export type ApprovalStatus = 'PENDING' | 'RELEASED' | 'REJECTED' | 'EXPIRED'

/** Enforcement action that triggered this approval requirement. */
export type EnforcementAction = 'HOLD_SESSION' | 'REQUIRE_APPROVAL' | 'DENY'

/**
 * A pending approval ticket requiring SOC analyst intervention.
 *
 * Generated by the Enforcement Engine when a session exceeds risk thresholds
 * and requires human authorization before execution can resume.
 */
export interface PendingApproval {
  /** Unique approval ticket identifier. */
  id: string
  /** ID of the agent session held pending approval. */
  session_id: string
  /** ID of the agent whose session is held. */
  agent_id: string
  /** The tool invocation that triggered the enforcement action. */
  tool_id: string
  /** Enforcement action that generated this ticket. */
  enforcement_action: EnforcementAction
  /** Current status of this approval ticket. */
  status: ApprovalStatus
  /** Human-readable reason for the hold. */
  reason: string
  /** Risk score at the time of hold (0–100). */
  risk_score: number
  /** ISO 8601 timestamp when the session was held. */
  created_at: string
  /** ISO 8601 timestamp when the ticket expires (if not acted upon). */
  expires_at?: string
  /** ID of the analyst who acted on this ticket (if resolved). */
  resolved_by?: string
  /** ISO 8601 timestamp of analyst action (if resolved). */
  resolved_at?: string
}
