/**
 * finding.ts — Finding domain types.
 *
 * Type contracts for behavioral detection findings surfaced by the
 * Detection Engine (ADR-017). These types will be populated when the
 * Findings API ships in PR #69 (Vertical Slice 2).
 *
 * Backend source: GET /api/v1/findings
 * Console surface: /findings — Findings & Alerts Console
 *
 * Feature gate: FINDINGS_ENABLED (src/config/featureFlags.ts)
 */

/** Severity level of a detection finding. */
export type FindingSeverity = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO'

/** MITRE ATT&CK tactic category for the finding. */
export type FindingCategory =
  | 'PROMPT_INJECTION'
  | 'DATA_EXFILTRATION'
  | 'PRIVILEGE_ESCALATION'
  | 'UNAUTHORIZED_TOOL'
  | 'SENSITIVE_FILE_ACCESS'
  | 'BROWSER_ABUSE'
  | 'SECRET_LEAKAGE'
  | 'MULTI_STEP_ATTACK'
  | 'UNKNOWN'

/** Status of a finding in the triage lifecycle. */
export type FindingStatus = 'OPEN' | 'ACKNOWLEDGED' | 'RESOLVED' | 'FALSE_POSITIVE'

/**
 * A security finding generated by the Detection Engine.
 * Represents a confirmed or suspected policy violation or anomaly.
 */
export interface Finding {
  /** Unique finding identifier. */
  id: string
  /** ID of the agent session where the finding occurred. */
  session_id: string
  /** ID of the agent that triggered the finding. */
  agent_id: string
  /** ID of the detection rule that fired. */
  rule_id: string
  /** Human-readable name of the rule. */
  rule_name: string
  /** Finding severity as assessed by the Detection Engine. */
  severity: FindingSeverity
  /** MITRE ATT&CK tactic or custom category. */
  category: FindingCategory
  /** Current triage status. */
  status: FindingStatus
  /** Human-readable description of the detected behavior. */
  description: string
  /** ISO 8601 timestamp when the finding was generated. */
  detected_at: string
  /** Optional list of MITRE ATT&CK technique IDs (e.g. ['T1059', 'T1056']). */
  mitre_techniques?: string[]
}
