"""Behavioral telemetry event taxonomy according to ADR-015."""

from enum import Enum


class EventDomain(str, Enum):
    """Major domain categories for behavioral telemetry events."""

    AGENT_LIFECYCLE = "AGENT_LIFECYCLE"
    TOOL_INVOCATION = "TOOL_INVOCATION"
    SECURITY_EVALUATION = "SECURITY_EVALUATION"
    GOVERNANCE_ACTION = "GOVERNANCE_ACTION"


class TelemetryEventType(str, Enum):
    """Standardized event taxonomy classification according to ADR-015."""

    # Agent Lifecycle Events
    AGENT_REGISTERED = "AGENT_LIFECYCLE.AGENT_REGISTERED"
    SESSION_STARTED = "AGENT_LIFECYCLE.SESSION_STARTED"
    SESSION_ENDED = "AGENT_LIFECYCLE.SESSION_ENDED"
    STATUS_CHANGED = "AGENT_LIFECYCLE.STATUS_CHANGED"

    # Tool Invocation Events
    TOOL_INVOCATION_REQUESTED = "TOOL_INVOCATION.INVOCATION_REQUESTED"
    PARAMETERS_VALIDATED = "TOOL_INVOCATION.PARAMETERS_VALIDATED"
    EXECUTION_STARTED = "TOOL_INVOCATION.EXECUTION_STARTED"
    EXECUTION_COMPLETED = "TOOL_INVOCATION.EXECUTION_COMPLETED"
    EXECUTION_FAILED = "TOOL_INVOCATION.EXECUTION_FAILED"

    # Security Evaluation Events
    SECURITY_AUTHORIZATION_CHECKED = "SECURITY_EVALUATION.AUTHORIZATION_CHECKED"
    POLICY_EVALUATED = "SECURITY_EVALUATION.POLICY_EVALUATED"
    SECURITY_THREAT_SCANNED = "SECURITY_EVALUATION.THREAT_SCANNED"
    RISK_SCORED = "SECURITY_EVALUATION.RISK_SCORED"

    # Governance Action Events
    GOVERNANCE_DECISION_FINALIZED = "GOVERNANCE_ACTION.DECISION_FINALIZED"
    OVERRIDE_APPLIED = "GOVERNANCE_ACTION.OVERRIDE_APPLIED"
    APPROVAL_HELD = "GOVERNANCE_ACTION.APPROVAL_HELD"
    AGENT_SUSPENDED = "GOVERNANCE_ACTION.AGENT_SUSPENDED"
