from enum import Enum


class DetectionCategory(str, Enum):
    PROMPT_SECURITY = "PROMPT_SECURITY"
    DATA_SECURITY = "DATA_SECURITY"
    TOOL_SECURITY = "TOOL_SECURITY"
    IDENTITY_SECURITY = "IDENTITY_SECURITY"
    BEHAVIORAL_SECURITY = "BEHAVIORAL_SECURITY"
    POLICY_SECURITY = "POLICY_SECURITY"
